In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
states = ["Hot", "Cold"]
observations = [1, 2, 3]

transition_matrix = np.array([
    [0.7, 0.3],
    [0.4, 0.6]
])

emission_matrix = np.array([
    [0.2, 0.4, 0.4],
    [0.5, 0.4, 0.1]
])

print("States:", states)
print("Transition Matrix:\n", transition_matrix)
print("Emission Matrix:\n", emission_matrix)

States: ['Hot', 'Cold']
Transition Matrix:
 [[0.7 0.3]
 [0.4 0.6]]
Emission Matrix:
 [[0.2 0.4 0.4]
 [0.5 0.4 0.1]]
